# Generated by Django 4.2.5 on 2023-09-25 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('registration_number', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('AVAILABLE', 'The car is available for sale.'), ('PENDING', 'The car is pending for sale.'), ('SOLD', 'The car is sold.'), ('UNAVAILABLE', 'The car is not available for sale.')], max_length=11)),
                ('description', models.TextField(blank=True, null=True)),
                ('odometer', models.IntegerField()),
                ('price', models.FloatField()),
                ('condition', models.CharField(choices=[('EXCELLENT', 'The vehicle looks new and is in excellent mechanical condition.'), ('GOOD', 'The vehicle has minor cosmetic defects and is in good mechanical condition.'), ('FAIR', 'The vehicle has some repairable cosmetic defects and is free of major mechanical problems.'), ('POOR', 'The vehicle has significant cosmetic defects and is in need of mechanical repairs.')], max_length=9)),
                ('prev_owner_count', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace_app.car_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Odometer_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_min', models.IntegerField()),
                ('odometer_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Price_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.FloatField()),
                ('price_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Preferred_Year_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_min', models.IntegerField()),
                ('year_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_detail', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wishlist', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cars', models.ManyToManyField(related_name='wishlists', to='marketplace_app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Seller_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Very good')])),
                ('comment', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ManyToManyField(blank=True, related_name='preferences', to='marketplace_app.car_brand')),
                ('fuel', models.ManyToManyField(blank=True, related_name='preferences', to='marketplace_app.fuel_type')),
                ('model', models.ManyToManyField(blank=True, related_name='preferences', to='marketplace_app.car_model')),
                ('odometer_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='marketplace_app.preferred_odometer_range')),
                ('price_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='marketplace_app.preferred_price_range')),
                ('transmission', models.ManyToManyField(blank=True, related_name='preferences', to='marketplace_app.transmission_type')),
                ('year_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='marketplace_app.preferred_year_range')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'The order is pending.'), ('COMPLETED', 'The order is completed.')], max_length=9)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace_app.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='car/<int:car_id>/uploads')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='marketplace_app.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='marketplace_app.fuel_type'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='marketplace_app.car_model'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ManyToManyField(related_name='cars', to='marketplace_app.transmission_type'),
        ),
        migrations.CreateModel(
            name='Buyer_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Very good')])),
                ('comment', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_ratings', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
