# Generated by Django 4.2.5 on 2023-09-26 22:27

from django.db import migrations, models
import marketplace_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[marketplace_app.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='preferred_year_range',
            name='year_max',
            field=models.IntegerField(validators=[marketplace_app.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='preferred_year_range',
            name='year_min',
            field=models.IntegerField(validators=[marketplace_app.models.validate_year]),
        ),
    ]
