# Generated by Django 4.2.5 on 2023-09-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0002_alter_car_year_alter_preferred_year_range_year_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'The order is pending.'), ('COMPLETED', 'The order is completed.')], default='PENDING', max_length=9),
        ),
    ]
