# Generated by Django 4.2.5 on 2023-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0004_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
