# Generated by Django 4.2.5 on 2023-10-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0005_user_detail_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='marketplace_app.transmission_type'),
            preserve_default=False,
        ),
    ]
