# Generated by Django 4.2.5 on 2023-10-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0005_user_detail_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='city_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
