# Generated by Django 4.2.5 on 2023-10-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0006_remove_car_transmission_car_transmission'),
        ('marketplace_app', '0006_user_detail_city_address'),
    ]

    operations = [
    ]
