# Generated by Django 4.2.5 on 2023-10-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0007_merge_20231027_1153'),
        ('marketplace_app', '0008_listing'),
    ]

    operations = [
    ]
